/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PAR_IMPAR_H_RPCGEN
#define _PAR_IMPAR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define PARIMPARPROG 0x20000000
#define PARIMPARVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PAR_IMPAR 1
extern  int * par_impar_1(int *, CLIENT *);
extern  int * par_impar_1_svc(int *, struct svc_req *);
extern int parimparprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PAR_IMPAR 1
extern  int * par_impar_1();
extern  int * par_impar_1_svc();
extern int parimparprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PAR_IMPAR_H_RPCGEN */
