/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NOTAS_H_RPCGEN
#define _NOTAS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define NOTASPROG 0x20000000
#define NOTASVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define OBTEM_NOTA 1
extern  double * obtem_nota_1(char **, CLIENT *);
extern  double * obtem_nota_1_svc(char **, struct svc_req *);
extern int notasprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define OBTEM_NOTA 1
extern  double * obtem_nota_1();
extern  double * obtem_nota_1_svc();
extern int notasprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NOTAS_H_RPCGEN */
