/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PRIMO_H_RPCGEN
#define _PRIMO_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define PRIMOPROG 0x20000000
#define PRIMOVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PRIMO 1
extern  int * primo_1(int *, CLIENT *);
extern  int * primo_1_svc(int *, struct svc_req *);
extern int primoprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PRIMO 1
extern  int * primo_1();
extern  int * primo_1_svc();
extern int primoprog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PRIMO_H_RPCGEN */
